
FROM python:3.11

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY .. .

CMD ["sh", "-c", "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"]

