version: '3'

services:
    db:
        image: mysql:8.0
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    django:
        build:
            context: .
            dockerfile: Dockerfile-django
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env

    telegram-bot:
        build:
            context: .
            dockerfile: Dockerfile-telegram-bot
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env

volumes:
    db_data:
