
version: '3'

services:
    db:
        env_file:
            - .env
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    django:
        env_file:
            - .env
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile-django
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        restart: always
        volumes:
            - static_volume:/static
        ports:
            - "8000:8000"
        depends_on:
            - db

    telegram-bot:
        env_file:
            - .env
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile-telegram-bot
        ports:
            - "8001:8001"
        depends_on:
            - db

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - static_volume:/static
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .ssl:/etc/nginx/ssl
        depends_on:
            - django

volumes:
    db_data:
    static_volume:
