version: '3'

services:
    db:
        image: mysql:8.0
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    django:
        build:
            context: ./compose
            dockerfile: Dockerfile-django
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    telegram-bot:
        build:
            context: ./compose
            dockerfile: Dockerfile-telegram-bot
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ngrok:
        build:
            context: ./compose
            dockerfile: Dockerfile-ngrok-ngrok
        ports:
            - "4040:4040"
        depends_on:
            - django
        env_file:
            - .env
        environment:
            NGROK_AUTH: ${NGROK_AUTH}
            NGROK_DOMAIN: ${WEBHOOK_URL}

volumes:
    db_data:
