
FROM python:3.11

WORKDIR /home/Task-Manager
COPY . .
COPY ./requirements.txt /home/Task-Manager/requirements.txt
RUN pip install -r requirements.txt

WORKDIR /home/Task-Manager/src

#RUN python manage.py collectstatic --noinput
CMD ["python", "manage.py", "runserver"]