# Generated by Django 5.0.6 on 2024-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID Telegram')),
                ('date', models.DateField(default=0, verbose_name='Дата задачи')),
                ('start_datetime', models.TimeField(default=0, verbose_name='Время начала задачи')),
                ('end_datetime', models.TimeField(default=0, verbose_name='Время окончания задачи')),
                ('title', models.CharField(max_length=150, verbose_name='Название задачи')),
                ('description', models.TextField(default='', verbose_name='Описание задачи')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('done', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Задача пользователя',
                'verbose_name_plural': 'Задачи пользователей',
            },
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
