# Generated by Django 5.0.6 on 2024-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_bot', '0002_task_delete_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BinaryField(default=False, verbose_name='Выполенна задача'),
        ),
    ]
