# Generated by Django 5.0.6 on 2024-05-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_bot', '0004_alter_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
    ]
