# Generated by Django 5.0.6 on 2024-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0003_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Выполенна задача'),
        ),
    ]
